{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: 测试失败\nassert 1 == 2", "trace": "self = <test_pytest_allure.test_allure_step.TestEditPage object at 0x0000020099B75D00>\n\n    @allure.story(\"test02\")\n    def test_2(self):\n        \"\"\"这是失败用例\"\"\"\n>       assert 1 == 2, \"测试失败\"\nE       AssertionError: 测试失败\nE       assert 1 == 2\n\ntest_pytest_allure\\test_allure_step.py:35: AssertionError"}, "description": "这是失败用例", "start": 1653038685686, "stop": 1653038685687, "uuid": "31df8732-8008-4684-a1df-86094c9b4acc", "historyId": "fe30877cc4c4197f8c54d6a03fd6b844", "testCaseId": "eb1661be6564ad6e453c0a0e80c3da94", "fullName": "test_pytest_allure.test_allure_step.TestEditPage#test_2", "labels": [{"name": "story", "value": "test02"}, {"name": "feature", "value": "test"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure_step"}, {"name": "subSuite", "value": "TestEditPage"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "19040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure_step"}]}