{"name": "test_with_issue_link", "status": "passed", "start": 1653276474694, "stop": 1653276474694, "uuid": "77934f6f-bb93-42d1-a055-e3867d99d29d", "historyId": "d29cb6d5bf6d7c0d1dd05ef00571fdc7", "testCaseId": "24fcc6540926c8854777f93e0e311964", "fullName": "test_pytest_allure.test_allure02#test_with_issue_link", "labels": [{"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure02"}], "links": [{"type": "issue", "url": "https://github.com/allure-framework/allure-python/issues/642", "name": "bug issue链接"}]}